repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/detailyang/pre-commit-shell
    rev: v1.0.6
    hooks:
    -   id: shell-lint
-   repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.7.1.1
    hooks:
    -   id: shellcheck
-   repo: https://github.com/scop/pre-commit-shfmt
    rev: v3.4.2-1
    hooks:
    # Choose one of:
      - id: shfmt-docker  # Docker image (requires Docker to run)
