#!/bin/bash

set -u

source reglages || exit 1

verif_deps()
{
    for outil in nc nmap paplay
    do
        { type $outil &> /dev/null ; } || { echo "manque $outil..." ; exit 1 ; } 
    done
}

clear

verif_deps

#verifications des fichiers de données nécessaires
if [ ! -f ${INSCRIPTIONS} ] ; then echo "manque fichier d'inscriptions ${INSCRIPTIONS}" ; exit 1 ; fi
if [ ! -f ${RFIDS_DOSSARDS} ] ; then echo "manque fichier de RFIDS-DOSSARDS ${RFIDS_DOSSARDS}" ; exit 1 ; fi

#re-écrit le fichier d'inscriptions avec des balises __VIDE__ dans la colonne du temps
awk -F'\t' '{ print $1"\t"$2"\t"$3"\t"$4"\t"$5"\t'${BALISE_TEMPS_VIDE}'\t"$7"\t"$8"\t"$9"\t"$10"\t"$11"\t"$12 }' $INSCRIPTIONS > ${INSCRIPTIONS}.buf

tail -n +2 ${INSCRIPTIONS}.buf > ${INSCRIPTIONS}.mod
#rm -f ${INSCRIPTIONS}.buf

inscrits=`wc -l ${INSCRIPTIONS}.mod | awk '{ print $1 }'`

echo ""
echo "***"
echo "*** $inscrits inscrit(s) dans $INSCRIPTIONS ..."
echo "***"
echo ""

tail -n +2 $INSCRIPTIONS | head -3
echo .
echo .
tail -n +2 $INSCRIPTIONS | tail -3

nb_rfids=`wc -l ${RFIDS_DOSSARDS} | awk '{ print $1 }'`

echo ""
echo ""
echo "***"
echo "*** $nb_rfids numeros de series RFID enregistrés"
echo "***"
echo ""

head -3 $RFIDS_DOSSARDS 
echo .
echo .
tail -n +2 $RFIDS_DOSSARDS | tail -3

echo ""
echo ""
echo "*** test du beep... appuyer sur ENTREE ***"
echo ""
echo ""

read ignore

paplay ${FICHIER_BEEP} || exit 1

echo ""
echo ""
echo "*** appuyer sur ENTREE au démarrage de la course "
echo "*** ATTENTION a l'effacement à suivre des donnees"
echo "*** précédentes dans $DOSSIER_URA"
echo ""

read ignore

t0=`date +%I:%M:%S`

rm -rf ${DOSSIER_URA} || exit 1

echo "démarrage de la course @ $t0"
echo "écriture de cette date dans ${FICHIER_T0}"

echo $t0 > ${FICHIER_T0} || exit 1
