#!/bin/bash

set -u

source reglages || exit 1

clear

#verifications des fichiers de données nécessaires
if [ ! -f ${INSCRIPTIONS} ] ; then echo "manque fichier d'inscriptions ${INSCRIPTIONS}" ; exit 1 ; fi
if [ ! -f ${RFIDS_DOSSARDS} ] ; then echo "manque fichier de RFIDS-DOSSARDS ${RFIDS_DOSSARDS}" ; exit 1 ; fi

#re-écrit le fichier d'inscriptions avec des balises __VIDE__ dans la colonne du temps
awk -F'\t' '{ print $1"\t"$2"\t"$3"\t"$4"\t"$5"\t'${BALISE_TEMPS_VIDE}'\t"$7"\t"$8"\t"$9"\t"$10"\t"$11"\t"$12 }' $INSCRIPTIONS > ${INSCRIPTIONS}.mod

nb_inscrs=`wc -l ${INSCRIPTIONS} | awk '{ print $1 }'`
#une ligne d'entête à soustraire
inscrits=$(($nb_inscrs-1))

echo ""
echo "***"
echo "*** $inscrits inscrit(s) dans $INSCRIPTIONS ..."
echo "***"
echo ""

tail -n +2 $INSCRIPTIONS | head -3
echo .
echo .
tail -n +2 $INSCRIPTIONS | tail -3

nb_rfids=`wc -l ${RFIDS_DOSSARDS} | awk '{ print $1 }'`

echo ""
echo ""
echo "***"
echo "*** $nb_rfids numeros de series RFID enregistrés"
echo "***"
echo ""

head -3 $RFIDS_DOSSARDS 
echo .
echo .
tail -n +2 $RFIDS_DOSSARDS | tail -3

echo ""
echo ""
echo "*** test du beep... appuyer sur ENTREE ***"
echo ""
echo ""

read ignore

paplay ${FICHIER_BEEP} || exit 1
