#!/bin/bash

set -u

# shellcheck disable=SC1091
source reglages || exit 1

nb_rfid_prev=0

if [ ! -d "$DOSSIER_URA" ]; then
	echo "dossier $DOSSIER_URA n'existe pas"
	exit 1
fi

#generer un fichier avec un RFID par ligne pour reference des rfids a chercher...

awk '{print $1}' <"${FICHIER_RFIDS_DOSSARDS}" >rfids.txt

while true; do
	cat "${DOSSIER_CROSS}/${DOSSIER_URA}"/ura* | grep -v "Automatic message" | sort -k1,1 -u | sort -k2,2 | awk '{ print $1" "$2 } ' >"${SYNTHESE}".tmp

	#filtrer les RFIDs qui ne sont pas dans le fichier rfid_dossards
	grep -f rfids.txt "${SYNTHESE}.tmp" >"${SYNTHESE}.2.tmp"
	rm -f "${SYNTHESE}.tmp"
	mv "${SYNTHESE}.2.tmp" "${SYNTHESE}"

	nb_rfid=$(wc -l "${SYNTHESE}" | awk '{ print $1}')
	#faire un bruit lorsque le nombre de RFID augmente
	if [ "$nb_rfid" -gt "$nb_rfid_prev" ]; then
		for ((i = 0; i < $((nb_rfid - nb_rfid_prev)); i++)); do
			echo -n "X"
			paplay "${FICHIER_BEEP}"
			sleep 0.1
		done
		nb_rfid_prev=$nb_rfid
	fi
	echo -n "."
	sleep 0.01
done
