#!/bin/bash

set -u

source reglages || exit 1

if [ ! -d $DOSSIER_URA ] ; then
    echo "dossier $DOSSIER_URA n'existe pas"
    exit 1
fi

cd $DOSSIER_URA || exit 1

while true
do
    cat ura* | grep -v "Automatic message" | sort -k1,1 -u | sort -k2,2 | awk '{ print $1" "$2 } '> ${SYNTHESE}
    echo -n "."
    sleep 1
done
