#!/bin/bash

set -u

source reglages || exit 1

#cherche une ligne du fichier correspondant au dossard $d et change le temps
function extrait_ligne()
{
    d=$1
    t=$2
    awk -F'\t' '{ if ($5=='"$d"') { print $0 }}' ${INSCRIPTIONS}.mod | sed "s/${BALISE_TEMPS_VIDE}/$t/g"
}

for fichier in $SYNTHESE $RFIDS_DOSSARDS
do
    if [ ! -f $fichier ] ; then
        echo "manque fichier $fichier"
        exit 1
    fi
done

#fabrique la base de données des RFIDS -> DOSSARDS
declare -A RFIDS_DOSSARDS

while read ligne
do
    RFID=`echo $ligne | awk '{ print $1}'`
    DOSSARD=`echo $ligne | awk '{ print $2}'`
    #echo "ajouter RFID $RFID -> $DOSSARD"
    RFIDS_DOSSARDS[$RFID]=$DOSSARD
done < $RFIDS_DOSSARDS

# for cle in "${!RFIDS_DOSSARDS[@]}"
# do
#     echo "$cle => ${RFIDS_DOSSARDS[$cle]}"
# done

while true
do
    #bloque une version du fichier pour travailler sur un fichier stabilisé
    cp ${SYNTHESE} ${SYNTHESE}.snapshot || exit 1

    #bien remettre la première ligne du fichier en place pour le logiciel de Franck
    echo -e "NOM\tPRENOM\tSEXE\tNAISSANCE\tNUMERO\tTEMPS\tCOURSE\tDISTANCE\tVILLE\tEMAIL\tCLUB\tLICENCE" > ${FICHIER_POUR_FRANCK}
    
    while read ligne
    do
        RFID=`echo $ligne | awk '{ print $1}'`
        TIME=`echo $ligne | awk '{ print $2}'`

        t0=`date -d "$T0" +%s`
        tf=`date -d "$TIME" +%s`
        dt=$(($tf-$t0))
        DTIME=`date -d "0000-01-01 $dt seconds" +%T`

        DOSSARD=${RFIDS_DOSSARDS[$RFID]}

        #echo $DTIME $DOSSARD

        extrait_ligne $DOSSARD $DTIME
    done < ${SYNTHESE}.snapshot >> ${FICHIER_POUR_FRANCK}

    echo -n "."
    sleep 5
done
