#!/bin/bash

export DOSSIER_CROSS=~/u3c

#0_init
export FICHIER_INSCRIPTIONS=${DOSSIER_CROSS}/docs/exemples/Inscriptions_TEST3.txt
export FICHIER_RFIDS_DOSSARDS=${DOSSIER_CROSS}/rfids_dossards

#1_rfids
export DOSSIER_URA=ura
export IP_JADAK_URA=192.168.0.3
export PORT_URA=9055

#2_filtre
export SYNTHESE=${DOSSIER_CROSS}/${DOSSIER_URA}/synthese_uras

#3_consolide
export FICHIER_T0=${DOSSIER_CROSS}/t0.txt
export FICHIER_POUR_FRANCK=${DOSSIER_CROSS}/resultats.txt

#reglages
export BALISE_TEMPS_VIDE=__VIDE__
export FICHIER_BEEP=bell.oga

#temps en secondes a enlever pour effacer le temps entre l arrivee et le detecteur
export DELTA_T=10
